var great_trail_spots={
"type": "FeatureCollection",
"name": "greattraillocations",
"coordinates": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "TITLE": "Buena Vista Park", "VISIBLE": 1, "City": "Alma", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Hiking w/ river views", "county": "Buffalo", "image": "https://www.visitpepin.com/wp-content/uploads/Overlook-at-Buena-Vista-Park-2-scaled.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.911491, 44.323637 ] } },
{ "type": "Feature", "properties": { "TITLE": "Merrick State Park", "VISIBLE": 1, "City": "Fountain City", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Camping w/ river access", "county": "Buffalo", "image": "https://www.mywisconsinspace.com/wp-content/uploads/2015/07/Merrick-State-Park31a-e1437643125403.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.754506, 44.154004 ] } },
{ "type": "Feature", "properties": { "TITLE": "Riecks Lake Park", "VISIBLE": 1, "City": "Alma", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Observation Deck", "county": "Buffalo", "image": "https://www.travelwisconsin.com/getContentAsset/96c04a93-1606-4e4d-93d4-719fb56bedf5/44fdae11-b262-452a-b144-600ede9d8ae7/538_Riecks_Viewing_Deck-1.webp?language=en" }, "geometry": { "type": "Point", "coordinates": [ -91.932678, 44.355226 ] } },
{ "type": "Feature", "properties": { "TITLE": "Tiffany Bottoms State Wildlife Area", "VISIBLE": 1, "City": "Nelson", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Wildlife Area, river", "county": "Buffalo", "image": "https://www.travelwisconsin.com/getContentAsset/19ff1ae6-7b6a-46a6-987a-1705a35d64dd/44fdae11-b262-452a-b144-600ede9d8ae7/Tiffany-1.webp?language=en" }, "geometry": { "type": "Point", "coordinates": [ -92.035388, 44.528001 ] } },
{ "type": "Feature", "properties": { "TITLE": "Whitman Dam Wildlife Area", "VISIBLE": 1, "City": "Cochrane", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Wildlife Area, wetlands", "county": "Buffalo", "image": "https://dnr.wisconsin.gov/sites/default/files/topic/images/Lands_Content_Image_WhitmanDamWA.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.807367, 44.171566 ] } },


{ "type": "Feature", "properties": { "TITLE": "Hogback Prairie State Natural Area", "VISIBLE": 1, "City": "Stueben", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "River/prairie hiking", "county": "Crawford", "image": "https://widnr.widen.net/content/vzhki6hlbb/jpeg/334_hogback.jpeg?position=c&color=cccccc&quality=80" }, "geometry": { "type": "Point", "coordinates": [ -90.881801, 43.217630 ] } },
{ "type": "Feature", "properties": { "TITLE": "Kickapoo River State Wildlife Area", "VISIBLE": 1, "City": "Wauzeka", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Wauzeka Unit of the Kickapoo River with hiking/river access", "county": "Crawford", "image": "https://embed.widencdn.net/img/widnr/om8kqmlqi0/exact/PooBCU_700x300.jpg?c=false&color=cccccc&position=c&quality=80" }, "geometry": { "type": "Point", "coordinates": [ -90.867552, 43.109354 ] } },
{ "type": "Feature", "properties": { "TITLE": "La Riviere Park", "VISIBLE": 1, "City": "Prairie du Chien", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Horseback riding and hiking", "county": "Crawford", "image": "https://cityofpdc.com/vertical/Sites/%7B2B4E3FAC-3791-4F66-96C1-96E5F2FDBF40%7D/uploads/La-Riviere-Horse-Camp_Web.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.102578, 43.021414 ] } },
{ "type": "Feature", "properties": { "TITLE": "Lock and Dam 9", "VISIBLE": 1, "City": "Lynxville", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Mississippi River dam w/ outlook", "county": "Crawford", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRks_P-L1grXAedpMOH2KtrQPgbdNpCE668DA&s" }, "geometry": { "type": "Point", "coordinates": [ -91.099011, 43.211093 ] } },
{ "type": "Feature", "properties": { "TITLE": "Rush Creek State Natural Area", "VISIBLE": 1, "City": "Ferryville", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Forest hiking w/ river views", "county": "Crawford", "image":"https://forestadaptation.org/sites/default/files/demo-images/RushSNA-3.png" }, "geometry": { "type": "Point", "coordinates": [ -91.137614, 43.376294 ] } },
{ "type": "Feature", "properties": { "TITLE": "St. Feriole Island Park", "VISIBLE": 1, "City": "Prairie du Chien", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Historic city park", "county": "Crawford", "image": "https://cityofpdc.com/vertical/Sites/%7B2B4E3FAC-3791-4F66-96C1-96E5F2FDBF40%7D/uploads/St-Feriole-Dousman.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.155396, 43.051015 ] } },

    
{ "type": "Feature", "properties": { "TITLE": "Duck Egg County Forest", "VISIBLE": 1, "City": "Viroqua", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Forest hiking and horseback riding", "county": "Vernon", "image": "https://www.alltrails.com/mugen/image/location-app-router?url=https%3A%2F%2Fimages.alltrails.com%2FeyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMTE1NjMzNTQxLzYyMjE4ZTcyNTIxOTI3ZGUxMmI3YjZhODQxOTJmMGM2LmpwZyIsImVkaXRzIjp7InRvRm9ybWF0Ijoid2VicCIsInJlc2l6ZSI6eyJ3aWR0aCI6IjEwODAiLCJoZWlnaHQiOiI3MDAiLCJmaXQiOiJjb3ZlciJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ%3D%3D&w=3840&q=90" }, "geometry": { "type": "Point", "coordinates": [ -91.003474, 43.587270 ] } },
{ "type": "Feature", "properties": { "TITLE": "Genoa National Fish Hatchery", "VISIBLE": 1, "City": "Genoa", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Fish hatchery and education center", "county": "Vernon", "image": "https://www.fws.gov/sites/default/files/2021-11/5x7.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.215529, 43.523875 ] } },
{ "type": "Feature", "properties": { "TITLE": "Kickapoo Valley Reserve", "VISIBLE": 1, "City": "La Farge", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Forest hiking, river access and visitor center", "county": "Vernon", "image": "https://driftlesswisconsin.com/wp-content/uploads/2023/05/kickapoo-river.jpg" }, "geometry": { "type": "Point", "coordinates": [ -90.625725, 43.595827 ] } },
{ "type": "Feature", "properties": { "TITLE": "Old Settler's Overlook", "VISIBLE": 1, "City": "Genoa", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "River overlook", "county": "Vernon", "image": "https://mississippivalleytraveler.com/wp-content/uploads/tn_Mississippi-River-at-River-Mile-682-07-Genoa-Overlook.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.220499, 43.614913 ] } },
{ "type": "Feature", "properties": { "TITLE": "Wildcat Mountain State Park", "VISIBLE": 1, "City": "Ontario", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Forest hiking, river access, camping and visitor center", "county": "Vernon", "image": "https://dnr.wisconsin.gov/sites/default/files/topic/Events/vistarail_500.jpg" }, "geometry": { "type": "Point", "coordinates": [ -90.574461, 43.698013 ] } },
{ "type": "Feature", "properties": { "TITLE": "Mt. Pisgah Hemlock-Hardwoods State Natural Area", "VISIBLE": 1, "City": "Ontario", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Forest hiking and camping", "county": "Vernon", "image": "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj5khZQPXyNuluJtgpvwYWM2Hb5mQF6TUuLT3wP6u9s4EB1V5wRN91xiMu0m2fpjAevX0wusT9zO2iGzW0nR_4pvl9vzT061FmRMyhpKkgpPnKumIVWuR1zYb34KqdPCuvRAYI49asjCMI/s16000-rw/mt+pisgah.jpg" }, "geometry": { "type": "Point", "coordinates": [ -90.580831, 43.687922] } },

    
{ "type": "Feature", "properties": { "TITLE": "Goose Island County Park", "VISIBLE": 1, "City": "La Crosse", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Camping, boat launch and hiking", "county": "La Crosse", "image": "https://www.travelwisconsin.com/getContentAsset/ac1df9d8-d634-4548-b2f8-3b8621a734e2/44fdae11-b262-452a-b144-600ede9d8ae7/goose-island-2.webp?language=en" }, "geometry": { "type": "Point", "coordinates": [ -91.228748, 43.734224 ] } },
{ "type": "Feature", "properties": { "TITLE": "Hixon Forest", "VISIBLE": 1, "City": "La Crosse", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Forest hiking and mountain-biking", "county": "La Crosse", "image": "https://www.travelwisconsin.com/getContentAsset/1b7d124d-0873-425b-b402-c1c2416646e9/44fdae11-b262-452a-b144-600ede9d8ae7/TabbedPOINavigatorCard/upper-hixon_TabbedPOINavigatorCard.webp?language=en" }, "geometry": { "type": "Point", "coordinates": [ -91.202602, 43.821573 ] } },
{ "type": "Feature", "properties": { "TITLE": "Riverside Park", "VISIBLE": 1, "City": "La Crosse", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "City park, river access and ferry rides", "county": "La Crosse", "image": "https://upload.wikimedia.org/wikipedia/commons/6/67/Riverside_park_aerial.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.255651, 43.817347 ] } },
{ "type": "Feature", "properties": { "TITLE": "Myrick Park", "VISIBLE": 1, "City": "La Crosse", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Nature center, playground and marsh hiking", "county": "La Crosse", "image": "https://www.uwlax.edu/contentassets/188c6d7903cb4c2fa317c799dff97c17/2020-uwl-fall-student-life-and-buildings-0498.jpg/Medium" }, "geometry": { "type": "Point", "coordinates": [ -91.225523, 43.820784 ] } },
{ "type": "Feature", "properties": { "TITLE": "McGilvray Seven Bridges Road", "VISIBLE": 1, "City": "Holmen", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Historic bridges", "county": "La Crosse", "image": "https://www.travelwisconsin.com/getContentAsset/182282fb-580c-487c-983b-20e2df26c6e4/44fdae11-b262-452a-b144-600ede9d8ae7/7bridgesrd.webp?language=en" }, "geometry": { "type": "Point", "coordinates": [ -91.306018, 44.021502 ] } },
{ "type": "Feature", "properties": { "TITLE": "Van Loon Floodplain Savanna State Natural Area", "VISIBLE": 1, "City": "Holmen", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "River access, limited camping and wetland area", "county": "La Crosse", "image": "https://embed.widencdn.net/img/widnr/gyornhmqcq/exact/vanloon.jpg?c=false&color=cccccc&position=c&quality=80" }, "geometry": { "type": "Point", "coordinates": [ -91.314088, 44.045437 ] } },
{ "type": "Feature", "properties": { "TITLE": "Norskedalen Nature and Heritage Center", "VISIBLE": 1, "City": "Coon Valley", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Norwegian heritage center and museum grounds", "county": "La Crosse", "image": "https://www.travelwisconsin.com/getContentAsset/0791ece9-99cb-4fa9-b2bf-bf3a793ef17e/44fdae11-b262-452a-b144-600ede9d8ae7/Norskedalen-Homestead.webp?language=en" }, "geometry": { "type": "Point", "coordinates": [ -90.989299, 43.737221 ] } },
{ "type": "Feature", "properties": { "TITLE": "Upper Mississippi River National Wildlife and Fish Refuge Visitor Center", "VISIBLE": 1, "City": "Onalaska", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Visitor Center location for a park with camping, boat launches and wetland areas", "county": "La Crosse", "image": "https://www.fws.gov/sites/default/files/styles/facebook_1200x630/public/banner_images/2021-05/FWCO%20banner.jpg?h=2b05aca7&itok=oX6qEThv" }, "geometry": { "type": "Point", "coordinates": [ -91.282634, 43.927507 ] } },


{ "type": "Feature", "properties": { "TITLE": "Great River State Trail", "VISIBLE": 1, "City": "Trempeleau", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Gravel path with historic bridges", "county": "Trempeleau", "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT9MNimxdfv7f3-DA0cwQR1X0oAG4xutGBSog&s" }, "geometry": { "type": "Point", "coordinates": [ -91.354366, 43.970054 ] } },
{ "type": "Feature", "properties": { "TITLE": "Perrot State Park", "VISIBLE": 1, "City": "Trempeleau", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Camping, forest hiking, nature center and river overlooks", "county": "Trempeleau", "image": "https://dnr.wisconsin.gov/sites/default/files/topic/Events/trempmt_500.jpg" }, "geometry": { "type": "Point", "coordinates": [ -91.481831, 44.026299 ] } },
{ "type": "Feature", "properties": { "TITLE": "Trempeleau Lakes State Wildlife Area", "VISIBLE": 1, "City": "Trempeleau", "DATE": null, "TYPEID": 0, "Peak_Heigh": 8586, "details": "Lake/river access hunting area", "county": "Trempeleau", "image": "https://www.fws.gov/sites/default/files/styles/facebook_1200x630/public/banner_images/2021-10/American_White_Pelicans_Kayaker_20191020_rezise.jpeg?h=5c8c18b6&itok=t7-8Ct40" }, "geometry": { "type": "Point", "coordinates": [ -91.415786, 43.993869 ] } },

    
    
    
    
]
};
 

